server:
  port: 8081

spring:
  kafka:
    consumer:
      bootstrap-servers: 192.168.110.133:9092
      group-id: my-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  redis:
    host: localhost
    port: 6377